# Generated by Django 5.0.1 on 2026-01-16 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JingleSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jingle_name",
                    models.CharField(
                        help_text="Display name (e.g., 'Tuesday Night Taco Promotion')",
                        max_length=200,
                    ),
                ),
                (
                    "jingle_filename",
                    models.CharField(
                        help_text="Actual audio file (e.g., 'jingle_12345.mp3')",
                        max_length=255,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="First day this jingle becomes active"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last day this jingle is active (null = no end)",
                        null=True,
                    ),
                ),
                (
                    "time_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time (e.g., 17:00 for 5pm)",
                        null=True,
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time (e.g., 22:00 for 10pm)",
                        null=True,
                    ),
                ),
                ("monday", models.BooleanField(default=True)),
                ("tuesday", models.BooleanField(default=True)),
                ("wednesday", models.BooleanField(default=True)),
                ("thursday", models.BooleanField(default=True)),
                ("friday", models.BooleanField(default=True)),
                ("saturday", models.BooleanField(default=True)),
                ("sunday", models.BooleanField(default=True)),
                (
                    "repeat_pattern",
                    models.CharField(
                        choices=[
                            ("occasional", "Occasional - Every 8-10 rounds"),
                            ("regular", "Regular - Every 5-7 rounds"),
                            ("often", "Often - Every 3-4 rounds"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Master on/off switch for this schedule"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority wins if multiple jingles qualify (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Jingle Schedule",
                "verbose_name_plural": "Jingle Schedules",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JinglePlayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jingle_filename", models.CharField(max_length=255)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                ("round_number", models.IntegerField()),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="play_history",
                        to="api.jingleschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jingle Play History",
                "verbose_name_plural": "Jingle Play History",
                "ordering": ["-played_at"],
            },
        ),
    ]
