# Generated by Django 5.0.1 on 2026-01-17 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_jingleschedule_venue_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        help_text="Unique venue name (e.g., 'The Admiral Rodney Southwell')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "num_players",
                    models.IntegerField(
                        default=25,
                        help_text="Default number of players for this venue",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        default="JBFqnCBsd6RMkjVDRZzb",
                        help_text="ElevenLabs voice ID for announcements",
                        max_length=100,
                    ),
                ),
                (
                    "selected_decades",
                    models.JSONField(
                        default=list,
                        help_text="Array of selected decades (e.g., ['60s', '70s', '80s'])",
                    ),
                ),
                (
                    "pub_logo",
                    models.URLField(
                        blank=True,
                        help_text="URL to pub logo image",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "social_platform",
                    models.CharField(
                        blank=True,
                        default="instagram",
                        help_text="Social media platform (instagram, facebook, tiktok, twitter)",
                        max_length=50,
                    ),
                ),
                (
                    "social_username",
                    models.CharField(
                        blank=True,
                        help_text="Social media username (without @)",
                        max_length=200,
                    ),
                ),
                (
                    "include_qr",
                    models.BooleanField(
                        default=False, help_text="Include QR code on bingo cards"
                    ),
                ),
                (
                    "prize_4corners",
                    models.CharField(
                        blank=True,
                        help_text="Prize for 4 corners (e.g., '£10 voucher')",
                        max_length=200,
                    ),
                ),
                (
                    "prize_first_line",
                    models.CharField(
                        blank=True,
                        help_text="Prize for first line (e.g., '£15 voucher')",
                        max_length=200,
                    ),
                ),
                (
                    "prize_full_house",
                    models.CharField(
                        blank=True,
                        help_text="Prize for full house (e.g., '£50 cash prize')",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Venue Configuration",
                "verbose_name_plural": "Venue Configurations",
                "ordering": ["venue_name"],
            },
        ),
    ]
