# Generated by Django 5.0.1 on 2026-01-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_venueconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="KaraokeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        help_text="Venue hosting this karaoke session", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting to Start"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="waiting",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                (
                    "avg_song_duration",
                    models.IntegerField(
                        default=240,
                        help_text="Average song duration in seconds for time estimation",
                    ),
                ),
                (
                    "auto_advance",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically advance to next singer when song completes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Karaoke Session",
                "verbose_name_plural": "Karaoke Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KaraokeQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Singer's name", max_length=200)),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Optional message to the crowd (e.g., 'Dedicated to my friends')",
                    ),
                ),
                (
                    "song_id",
                    models.CharField(
                        help_text="Karafun song ID or custom identifier", max_length=100
                    ),
                ),
                (
                    "song_title",
                    models.CharField(help_text="Song title", max_length=300),
                ),
                ("artist", models.CharField(help_text="Artist name", max_length=200)),
                (
                    "duration",
                    models.IntegerField(
                        default=240, help_text="Song duration in seconds"
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to instrumental audio track",
                        max_length=500,
                    ),
                ),
                (
                    "lyrics_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to synchronized lyrics (LRC format)",
                        max_length=500,
                    ),
                ),
                (
                    "position",
                    models.IntegerField(help_text="Position in queue (1 = next up)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting in Queue"),
                            ("singing", "Currently Singing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status in queue",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session this queue entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="api.karaokesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Karaoke Queue Entry",
                "verbose_name_plural": "Karaoke Queue Entries",
                "ordering": ["session", "position"],
            },
        ),
    ]
