# Generated by Django 5.0.7 on 2026-01-20 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_karaokesession_karaokequeue"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Emoji o clase de icono", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Quiz Genre",
                "verbose_name_plural": "Quiz Genres",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PubQuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_name", models.CharField(max_length=200)),
                ("host_name", models.CharField(default="Perfect DJ", max_length=200)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_rounds",
                    models.IntegerField(default=6, help_text="4-8 rounds typical"),
                ),
                ("questions_per_round", models.IntegerField(default=10)),
                (
                    "duration_minutes",
                    models.IntegerField(default=120, help_text="90-180 minutos típico"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registration", "Registration Open"),
                            ("voting", "Genre Voting"),
                            ("ready", "Ready to Start"),
                            ("in_progress", "In Progress"),
                            ("halftime", "Halftime Break"),
                            ("buzzer_round", "Buzzer Round"),
                            ("completed", "Completed"),
                        ],
                        default="registration",
                        max_length=20,
                    ),
                ),
                ("current_round", models.IntegerField(default=0)),
                ("current_question", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_hashtag",
                    models.CharField(
                        blank=True, default="#PerfectDJQuiz", max_length=100
                    ),
                ),
                (
                    "social_handle",
                    models.CharField(blank=True, default="@PerfectDJ", max_length=100),
                ),
                (
                    "selected_genres",
                    models.ManyToManyField(blank=True, to="api.quizgenre"),
                ),
            ],
            options={
                "verbose_name": "Pub Quiz Session",
                "verbose_name_plural": "Pub Quiz Sessions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GenreVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1, help_text="1 = favorito, 5 = menos favorito"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.quizgenre"
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("question_number", models.IntegerField()),
                ("question_text", models.TextField()),
                ("correct_answer", models.CharField(max_length=500)),
                ("alternative_answers", models.JSONField(blank=True, default=list)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("picture", "Picture Round"),
                            ("music", "Music/Audio"),
                            ("buzzer", "Buzzer Question"),
                            ("bonus", "Bonus"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField(blank=True)),
                ("points", models.IntegerField(default=1)),
                ("hints", models.TextField(blank=True)),
                (
                    "fun_fact",
                    models.TextField(
                        blank=True,
                        help_text="Dato curioso después de revelar respuesta",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.quizgenre",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="api.pubquizsession",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number", "question_number"],
                "unique_together": {("session", "round_number", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="QuizTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=200)),
                ("table_number", models.IntegerField(blank=True, null=True)),
                (
                    "num_players",
                    models.IntegerField(default=4, help_text="4-6 jugadores típico"),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("social_handle", models.CharField(blank=True, max_length=100)),
                (
                    "followed_social",
                    models.BooleanField(
                        default=False, help_text="¿Siguió redes sociales?"
                    ),
                ),
                ("total_score", models.IntegerField(default=0)),
                (
                    "bonus_points",
                    models.IntegerField(
                        default=0, help_text="Por seguir redes, buzzers, etc."
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genre_votes",
                    models.ManyToManyField(
                        blank=True, through="api.GenreVote", to="api.quizgenre"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="api.pubquizsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz Team",
                "verbose_name_plural": "Quiz Teams",
                "ordering": ["-total_score", "team_name"],
                "unique_together": {("session", "team_name")},
            },
        ),
        migrations.AddField(
            model_name="genrevote",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.quizteam"
            ),
        ),
        migrations.CreateModel(
            name="BuzzerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="UUID o MAC del buzzer", max_length=100, unique=True
                    ),
                ),
                (
                    "device_name",
                    models.CharField(help_text="Ej: Team1Buzzer", max_length=100),
                ),
                ("is_paired", models.BooleanField(default=False)),
                ("last_paired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "battery_level",
                    models.IntegerField(blank=True, help_text="0-100%", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buzzers",
                        to="api.quizteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buzzer Device",
                "verbose_name_plural": "Buzzer Devices",
            },
        ),
        migrations.CreateModel(
            name="QuizRound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("round_name", models.CharField(max_length=200)),
                ("is_completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_buzzer_round", models.BooleanField(default=False)),
                ("is_halftime_before", models.BooleanField(default=False)),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.quizgenre",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rounds",
                        to="api.pubquizsession",
                    ),
                ),
            ],
            options={
                "ordering": ["round_number"],
                "unique_together": {("session", "round_number")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="genrevote",
            unique_together={("team", "genre")},
        ),
        migrations.CreateModel(
            name="TeamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(blank=True, null=True)),
                ("points_awarded", models.IntegerField(default=0)),
                ("buzz_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "buzz_order",
                    models.IntegerField(
                        blank=True, help_text="1 = primero en presionar", null=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_answers",
                        to="api.quizquestion",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.quizteam",
                    ),
                ),
            ],
            options={
                "ordering": ["question__round_number", "question__question_number"],
                "unique_together": {("team", "question")},
            },
        ),
    ]
