# Generated by Django 5.0.1 on 2026-01-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_bingosession_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bingosession",
            name="logo_url",
            field=models.TextField(
                blank=True,
                help_text="URL to pub logo (supports data URIs for uploaded images)",
                null=True,
            ),
        ),
    ]
