# Generated by Django 5.0.1 on 2026-01-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_bingosession_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        help_text="UUID of the task",
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        help_text="Type: 'card_generation', 'jingle_generation'",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="pending",
                        help_text="Status: pending, processing, completed, failed",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, help_text="Progress percentage (0-100)"
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        blank=True, help_text="Current processing step", max_length=100
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.JSONField(
                        blank=True, help_text="Success result data", null=True
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, help_text="Error message if failed"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, help_text="Additional task parameters", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-started_at"],
                        name="api_tasksta_status_59f507_idx",
                    ),
                    models.Index(
                        fields=["task_type", "-started_at"],
                        name="api_tasksta_task_ty_14af93_idx",
                    ),
                ],
            },
        ),
    ]
