# Generated by Django 5.0.1 on 2026-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_bingosession_game_number_bingosession_pdf_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingosession",
            name="genres",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected genres (e.g., ['Rock', 'Pop', 'Dance']). Empty means all genres.",
            ),
        ),
    ]
