# Generated by Django 5.0.1 on 2026-02-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_genres_to_bingo_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlindDateSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        default="TEMP0000",
                        editable=False,
                        help_text="Random 8-character code for URL/QR access",
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("venue_name", models.CharField(max_length=200)),
                ("host_name", models.CharField(default="Celia Slack", max_length=200)),
                (
                    "min_players",
                    models.IntegerField(
                        default=5, help_text="Minimum players to start"
                    ),
                ),
                (
                    "answer_time_seconds",
                    models.IntegerField(
                        default=120, help_text="Seconds to answer each question"
                    ),
                ),
                (
                    "max_funny_shown",
                    models.IntegerField(
                        default=3, help_text="Top N funniest answers read aloud"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lobby", "Lobby — Waiting for Players"),
                            ("in_progress", "In Progress — Playing Rounds"),
                            ("between_rounds", "Between Rounds"),
                            ("completed", "Completed"),
                        ],
                        default="lobby",
                        max_length=20,
                    ),
                ),
                (
                    "current_player_idx",
                    models.IntegerField(default=0, help_text="Index in player queue"),
                ),
                (
                    "current_question_idx",
                    models.IntegerField(
                        default=0, help_text="Which question (0-2) of current player"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Blind Date Session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlindDatePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(
                        help_text="Short self-description", max_length=300
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        editable=False,
                        help_text="Temporary anonymous session token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("question_1", models.CharField(blank=True, max_length=200)),
                ("question_2", models.CharField(blank=True, max_length=200)),
                ("question_3", models.CharField(blank=True, max_length=200)),
                ("round_completed", models.BooleanField(default=False)),
                ("queue_order", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="api.blinddatesession",
                    ),
                ),
            ],
            options={
                "ordering": ["queue_order", "joined_at"],
                "unique_together": {("session", "nickname")},
            },
        ),
        migrations.CreateModel(
            name="BlindDateAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_index",
                    models.IntegerField(help_text="0, 1, or 2 — which question"),
                ),
                ("answer_text", models.TextField(max_length=500)),
                (
                    "humor_score",
                    models.IntegerField(
                        blank=True, help_text="AI humor rating 1-10", null=True
                    ),
                ),
                (
                    "ai_commentary",
                    models.TextField(
                        blank=True, help_text="AI sarcastic remark about this answer"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "answerer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_answers",
                        to="api.blinddateplayer",
                    ),
                ),
                (
                    "question_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_answers",
                        to="api.blinddateplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["-humor_score"],
                "unique_together": {("question_player", "question_index", "answerer")},
            },
        ),
        migrations.CreateModel(
            name="BlindDateLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_given",
                        to="api.blinddateplayer",
                    ),
                ),
                (
                    "to_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes_received",
                        to="api.blinddateplayer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="api.blinddatesession",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_player", "to_player")},
            },
        ),
    ]
