name: music-bingo
region: lon

services:
  - name: backend
    github:
      repo: 1di210299/Music_Bingo
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    http_port: 8080
    
    routes:
      - path: /
    
    envs:
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_VOICE_ID
        scope: RUN_TIME
        value: "21m00Tcm4TlvDq8ikWAM"
      - key: VENUE_NAME
        scope: RUN_TIME
        value: "Music Bingo"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

  - name: frontend
    github:
      repo: 1di210299/Music_Bingo
      branch: main
      deploy_on_push: true
    
    source_dir: frontend
    environment_slug: node-js
    http_port: 8080
    
    routes:
      - path: /
    
    envs:
      - key: BACKEND_URL
        scope: RUN_TIME
        value: ${backend.PUBLIC_URL}
