name: music-bingo
region: lon

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: backend
        preserve_path_prefix: true
    - match:
        path:
          prefix: /data
      component:
        name: backend
        preserve_path_prefix: true
    - match:
        path:
          prefix: /
      component:
        name: frontend
        preserve_path_prefix: true

services:
  - name: backend
    github:
      repo: DTv2-1/Music_Bingo
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-1gb-fixed  # 1GB RAM, $10/month
    
    envs:
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_VOICE_ID
        scope: RUN_TIME
        value: "21m00Tcm4TlvDq8ikWAM"
      - key: VENUE_NAME
        scope: RUN_TIME
        value: "Music Bingo"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET

  - name: frontend
    github:
      repo: DTv2-1/Music_Bingo
      branch: main
      deploy_on_push: true
    
    source_dir: frontend
    environment_slug: node-js
    http_port: 8080
    instance_size_slug: apps-s-1vcpu-0.5gb  # Keep frontend at 512MB, $5/month
    
    envs:
      - key: BACKEND_URL
        scope: RUN_TIME
        value: ${APP_URL}
